### ISSUE TITLE
Error: Cannot find module 'editions'

### ISSUE THREAD

**Issue by tony90018** [bevry/getmac#39]
when used 
`require('getmac')`
Error:
`Uncaught Error: Cannot find module 'editions'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (D:\wamp64\www\GZPC\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\wamp64\www\GZPC\node_modules\getmac\index.js:4:18)
    at Object.<anonymous> (D:\wamp64\www\GZPC\node_modules\getmac\index.js:6:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)`
How do I solve it?

**Comment by balupton** [comment]
How do you expect me to be able to solve your issue, without any knowledge of the node version and environment you are running it on

**Comment by jung-kim** [comment]
Hi, I think https://github.com/FredrikNoren/ungit/issues/1130#issuecomment-415367258 is related to this issue.  Perhaps, @guillaumedavidphd or @SDohle can share more details?

> ungit@1.4.32
> node@10.3.0
> npm@6.4.0
> os: Win10

(ungit@1.4.32 `package-lock.json`  is below)
```
    "getmac": {
      "version": "1.4.1",
      "resolved": "https://registry.npmjs.org/getmac/-/getmac-1.4.1.tgz",
      "integrity": "sha512-mQp+8D+grQX0gG8EJn6VfH0PxE56ZKNsTguOMxPShAiVk9lvH8Ey36eXepG705Ac1HCsvaSrQ/6bPHZ0++F/Mg==",
      "requires": {
        "editions": "1.3.4",
        "extract-opts": "3.3.1"
      },
      "dependencies": {
        "editions": {
          "version": "1.3.4",
          "resolved": "https://registry.npmjs.org/editions/-/editions-1.3.4.tgz",
          "integrity": "sha512-gzao+mxnYDzIysXKMQi/+M1mjy/rjestjg6OPoYTtI+3Izp23oiGZitsl9lPDPiTGXbcSIk1iJWhliSaglxnUg=="
        }
      }
    },
```

**Comment by balupton** [comment]
Hrmm. Ant chance of getting what is using getmac to update to getmac 1.4.4? As 1.4.4 has changes to the editions dependency that could help with this issue

**Comment by balupton** [comment]
should be fixed with getmac 1.4.5

**Comment by tony90018** [comment]
node: v10.8.0
npm:6.2.0
os:win8.1
getmac:1.4.4
editions:2.0.0

**Comment by balupton** [comment]
this should now be resolved
