### ISSUE TITLE
This fails on illumos/solaris/freebsd

### ISSUE THREAD

**Issue by sjorge** [bevry/getmac#45]
```
[root@amethyst ~]# getmac-node
Error: could not determine the mac address from:
lo0: flags=2001000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv4,VIRTUAL> mtu 8232 index 1
        inet 127.0.0.1 netmask ff000000
net0: flags=40201000843<UP,BROADCAST,RUNNING,MULTICAST,IPv4,CoS,L3PROTECT> mtu 1500 index 2
        inet 10.23.10.218 netmask ffffff00 broadcast 10.23.10.255
        ether 0:22:6:a:0:da
lo0: flags=2002000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv6,VIRTUAL> mtu 8252 index 1
        inet6 ::1/128
net0: flags=40202004841<UP,RUNNING,MULTICAST,DHCP,IPv6,CoS,L3PROTECT> mtu 1500 index 2
        inet6 fe80::222:6ff:fe0a:da/10
        ether 0:22:6:a:0:da
net0:1: flags=40202000841<UP,RUNNING,MULTICAST,IPv6,CoS,L3PROTECT> mtu 1500 index 2
        inet6 2001:470:7ee7:10::218/64
net0:2: flags=40202080840<RUNNING,MULTICAST,ADDRCONF,IPv6,CoS,L3PROTECT> mtu 1500 index 2
        inet6 ::/0

    at extractMac (/opt/local/lib/node_modules/getmac/edition-esnext/index.js:85:13)
    at /opt/local/lib/node_modules/getmac/edition-esnext/index.js:102:14
    at ChildProcess.exithandler (child_process.js:268:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

Not sure how hard to fix this is.

**Comment by sjorge** [comment]
Same for freebsd :(

FreeBSD:
```
sjorge@hydrogen:~ % ifconfig -a
vtnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=c00b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,LINKSTATE>
	ether 00:22:06:05:00:0a
	hwaddr 00:22:06:05:00:0a
	inet 192.168.0.10 netmask 0xffffff00 broadcast 192.168.0.255
	inet6 fe80::222:6ff:fe05:a%vtnet0 prefixlen 64 scopeid 0x1
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet 10Gbase-T <full-duplex>
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x7
	inet 127.0.0.1 netmask 0xff000000
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo
```

illumos:
```
lo0: flags=2001000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv4,VIRTUAL> mtu 8232 index 1
        inet 127.0.0.1 netmask ff000000
net0: flags=40201000843<UP,BROADCAST,RUNNING,MULTICAST,IPv4,CoS,L3PROTECT> mtu 1500 index 2
        inet 10.23.10.218 netmask ffffff00 broadcast 10.23.10.255
        ether 0:22:6:a:0:da
lo0: flags=2002000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv6,VIRTUAL> mtu 8252 index 1
        inet6 ::1/128
net0: flags=40202004841<UP,RUNNING,MULTICAST,DHCP,IPv6,CoS,L3PROTECT> mtu 1500 index 2
        inet6 fe80::222:6ff:fe0a:da/10
        ether 0:22:6:a:0:da
net0:1: flags=40202000841<UP,RUNNING,MULTICAST,IPv6,CoS,L3PROTECT> mtu 1500 index 2
        inet6 2001:470:7ee7:10::218/64
net0:2: flags=40202080840<RUNNING,MULTICAST,ADDRCONF,IPv6,CoS,L3PROTECT> mtu 1500 index 2
        inet6 ::/0
```

**Comment by sjorge** [comment]
Using this regex does seem to return a mac, the interface filter also seems broken
```(?:[a-z0-9]{1,2}[:\-]){5}[a-z0-9]{1,2}```

**Comment by balupton** [comment]
please try v4
